const CLEAR_CART = "CLEAR_CART";
const REMOVE = "REMOVE";
const INCREASE = "INCREASE";
const DECREASE = "DECREASE";
const GET_TOTALS = "GET_TOTALS";

export { REMOVE, CLEAR_CART, INCREASE, DECREASE, GET_TOTALS };
